<?php
// TESTI ITA
// HOME PAGE
$lang["msg_home_title"] = "romec Stampi";
// PAGINA CHI SIAMO
$lang["msg_chisiamo_title"] = "chi siamo";
$lang["msg_chisiamo_text"] = "<p>Nata nel 1979 per volontà dei fratelli Romele, Romec inizia la propria attività svolgendo lavorazioni di meccanica tradizionale, per poi effettuare anche riparazioni e ritocchi su stampi usurati, specializzandosi sempre più anche nella loro progettazione e costruzione. Con queste basi e grazie all’esperienza maturata, l’azienda è oggi in grado di sviluppare stampi per pressofusione in getti di alluminio e zama, stampi per lo stampaggio a caldo di particolari in ottone e ferro, stampi per iniezione gomma e plastica, oltre ad attrezzature di precisione.</p><p>In azienda operano attualmente una quindicina di persone qualificate e specializzate, impiegate nelle fasi di progettazione in ufficio tecnico, e nel reparto produttivo dove sono presenti evolute macchine a controllo numerico ad alta velocità per le lavorazioni di fresatura, di tornitura ed elettroerosione, che hanno portato a significativi risultati in termini di qualità, precisione e tempi di realizzazione dei propri stampi, garantendo tecnologia di processo e qualità di prodotto. A guidare questo gruppo di lavoro i due soci, Giacomo Romele e Margherita Bonvincini, responsabili della parte tecnica e amministrativa.</p><p>Attenta e sensibile all’evoluzione del proprio settore, alle esigenze del proprio personale, nonché all’importanza della qualità del proprio prodotto, la stessa Romec ha implementato e confermato da tempo un Sistema di Gestione Integrato Qualità –Salute e Sicurezza, come previsto dalla Norme Uni EN ISO 9001-2008 e Ohsas 18001-2007, oltre ad aver adottato e diffuso in azienda le Buone Prassi per la Responsabilità Sociale. Un’attenzione e un approccio operativo positivamente riconosciuti dai propri clienti, tanto in ambito nazionale quanto internazionale.</p>";
// PAGINA PROGETTAZIONE
$lang["msg_progettazione_title"] = "progettazione";
$lang["msg_progettazione_text"] = "<p>PROGETTAZIONE: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>";
// PAGINA COSTRUZIONE
$lang["msg_costruzione_title"] = "costruzione";
$lang["msg_costruzione_text"] = "<p>COSTRUZIONE: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>";
// PAGINA STAMPI
$lang["msg_stampi_title"] = "stampi";
$lang["msg_stampi_text"] = "<p>STAMPI: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>";
// PAGINA CONTATTI
$lang["msg_contatti_title"] = "contatti";
$lang["msg_contatti_text"] = "<p class='info'>Compila il form qui a fianco per chiederci informazioni o collaborazioni.</p>";